### ISSUE TITLE
Server crashes (1.16.5) (Minecarts and Monsters modpack)

### ISSUE THREAD

**Issue by NebulaBC** [PersonTheCat/OreStoneVariants#159]
Every time I try to start this modpack, with default configs (nothing changed) the server crashes because of OreStoneVarients

the error is
```
[18:36:15] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
Ore Stone Variants (osv) encountered an error during the load_registries event phase
§7com.personthecat.orestonevariants.exception.MissingElementException: There are no properties named "quark_biotite_ore." Fix your property group.
]
at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:269) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:202) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292] {}
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292] {}
at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.19.jar:36.2] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.19.jar:?] {}
at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.19.jar:?] {}
at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.19.jar:?] {}
```

**Comment by PersonTheCat** [comment]
Hey, this is user error and it's also for an unsupported version of the mod (6.2--the latest is 7.6). If this is happening out of the box for Minecarts and Monsters, you should reach out to the authors and have them fix it. It's just a configuration issue with osv-common.hjson. Also, please ask them to update to 7.6 as I 6.2 is such a different mod internally that I can't realistically support both of them. 

If you need anything else, please reach out on Discord. https://discord.gg/UNsXfvA

**Comment by NebulaBC** [comment]
Thank you, I will reach out to them. I just assumed it was something with the mod because I could not find the file that it was talking about. With the knowledge that it is in osv-common I will be able to fix it myself. I will also submit an issue with them about the version and file (embarrassing that their default config out of the box does not even boot)
